"""HoloLab wire protocol.

Every WebSocket message is a JSON envelope carrying a discriminated payload.
See docs/architecture.md#protocol.
"""

from hololab.protocol.envelope import (
    Envelope,
    decode,
    encode,
    negotiate_version,
)
from hololab.protocol.messages import (
    ArtifactDeleteReq,
    ArtifactDeleteResp,
    HandleCheckItem,
    HandleCheckReq,
    HandleCheckResp,
    HandleCheckResult,
    HandleLocateReq,
    HandleLocateResp,
    HandleRegister,
    Heartbeat,
    JobAck,
    JobAssign,
    JobCancel,
    JobDone,
    JobFail,
    JobFailReason,
    JobLog,
    JobProgress,
    JobUpdate,
    LogChunk,
    NodeConfigGetReq,
    NodeConfigGetResp,
    NodeConfigSetReq,
    NodeConfigSetResp,
    NodeMetrics,
    NodeOffline,
    NodeOnline,
    PacksUpdated,
    PreviewReady,
    Register,
    RegisterErr,
    RegisterOk,
    WorkflowUpdated,
)

__all__ = [
    "ArtifactDeleteReq",
    "ArtifactDeleteResp",
    "Envelope",
    "HandleCheckItem",
    "HandleCheckReq",
    "HandleCheckResp",
    "HandleCheckResult",
    "HandleLocateReq",
    "HandleLocateResp",
    "HandleRegister",
    "Heartbeat",
    "JobAck",
    "JobAssign",
    "JobCancel",
    "JobDone",
    "JobFail",
    "JobFailReason",
    "JobLog",
    "JobProgress",
    "JobUpdate",
    "LogChunk",
    "NodeConfigGetReq",
    "NodeConfigGetResp",
    "NodeConfigSetReq",
    "NodeConfigSetResp",
    "NodeMetrics",
    "NodeOffline",
    "NodeOnline",
    "PacksUpdated",
    "PreviewReady",
    "Register",
    "RegisterErr",
    "RegisterOk",
    "WorkflowUpdated",
    "decode",
    "encode",
    "negotiate_version",
]
